import { Articulo } from "./articulo";

export const ARTICULOS: Articulo[] = [
  {
    id: "m1",
    name: "Galaxy A32",
    imageUrl: "images/m1.jpg",
    currentPrice: 229,
    previousPrice: 269,
    rating: 4.4,
    reviewCount: 1200,
    deliveryDate: new Date("2025-11-04"),
    deliveryPrice: 0,
    otherShippingOptions: true
  },
  {
    id: "m2",
    name: "Oppo A94",
    imageUrl: "images/m2.jpg",
    currentPrice: 269,
    previousPrice: 269,
    rating: 4.3,
    reviewCount: 980,
    deliveryDate: new Date("2025-11-07"),
    deliveryPrice: 0,
    otherShippingOptions: false
  },
  {
    id: "m3",
    name: "Galaxy S22",
    imageUrl: "images/m3.jpg",
    currentPrice: 859,
    previousPrice: 955,
    rating: 4.7,
    reviewCount: 3200,
    deliveryDate: new Date("2025-11-07"),
    deliveryPrice: 0,
    otherShippingOptions: true
  },
  {
    id: "m4",
    name: "Apple iPhone",
    imageUrl: "images/m4.jpg",
    currentPrice: 339,
    previousPrice: 339,
    rating: 4.8,
    reviewCount: 5400,
    deliveryDate: new Date("2025-11-05"),
    deliveryPrice: 2,
    otherShippingOptions: true
  },
  {
    id: "m5",
    name: "Galaxy Z Flip4",
    imageUrl: "images/m5.jpg",
    currentPrice: 1990,
    previousPrice: 2487,
    rating: 4.6,
    reviewCount: 1900,
    deliveryDate: new Date("2025-11-04"),
    deliveryPrice: 0,
    otherShippingOptions: true
  },
  {
    id: "m6",
    name: "Note 11",
    imageUrl: "images/m6.jpg",
    currentPrice: 300,
    previousPrice: 300,
    rating: 4.2,
    reviewCount: 850,
    deliveryDate: new Date("2025-11-06"),
    deliveryPrice: 0,
    otherShippingOptions: false
  },
  {
    id: "m7",
    name: "Realme 9",
    imageUrl: "images/m7.jpg",
    currentPrice: 300,
    previousPrice: 400,
    rating: 4.5,
    reviewCount: 1500,
    deliveryDate: new Date("2025-11-07"),
    deliveryPrice: 0,
    otherShippingOptions: true
  },
  {
    id: "p1",
    name: "Asus Zen",
    imageUrl: "images/p1.jpg",
    currentPrice: 900,
    previousPrice: 900,
    rating: 4.3,
    reviewCount: 950,
    deliveryDate: new Date("2025-11-05"),
    deliveryPrice: 0,
    otherShippingOptions: true
  },
  {
    id: "p2",
    name: "HP Pavillion",
    imageUrl: "images/p2.jpg",
    currentPrice: 750,
    previousPrice: 788,
    rating: 4.1,
    reviewCount: 600,
    deliveryDate: new Date("2025-11-06"),
    deliveryPrice: 4,
    otherShippingOptions: false
  },
  {
    id: "p3",
    name: "MacBook",
    imageUrl: "images/p3.jpg",
    currentPrice: 1115,
    previousPrice: 1115,
    rating: 4.9,
    reviewCount: 6800,
    deliveryDate: new Date("2025-11-07"),
    deliveryPrice: 0,
    otherShippingOptions: true
  },
  {
    id: "t1",
    name: "Xiaomi P1E",
    imageUrl: "images/t1.jpg",
    currentPrice: 300,
    previousPrice: 341,
    rating: 4.4,
    reviewCount: 1200,
    deliveryDate: new Date("2025-11-04"),
    deliveryPrice: 0,
    otherShippingOptions: true
  },
  {
    id: "t2",
    name: "Toshiba 55UAG",
    imageUrl: "images/t2.jpg",
    currentPrice: 450,
    previousPrice: 450,
    rating: 4.3,
    reviewCount: 650,
    deliveryDate: new Date("2025-11-05"),
    deliveryPrice: 0,
    otherShippingOptions: false
  },
  {
    id: "t3",
    name: "Samsung UE305",
    imageUrl: "images/t3.jpg",
    currentPrice: 350,
    previousPrice: 380,
    rating: 4.5,
    reviewCount: 2100,
    deliveryDate: new Date("2025-11-07"),
    deliveryPrice: 3,
    otherShippingOptions: true
  }
];
